config/routes.rb
Lsn::Application.routes.draw do

scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

  resources :attachments

  resources :games

  resources :scores

  resources :professors

  resources :decks

  resources :courses

  resources :karteikartes

  match "/students/admin", :to => "Students#admin"
  resources :students
  
  root to: 'students#index'
  

  match '*path', to: redirect("/#{I18n.locale}/no_path")

  end
  match '*path', to: redirect { |params, request| "/#{I18n.default_locale}#{request.fullpath}" }
  match '', to: redirect("/#{I18n.default_locale}")

  match 'de', to: redirect("/de/students")
  match 'en', to: redirect("/en/students")

end

app/models/karteikarte.rb
class Karteikarte < ActiveRecord::Base
  attr_accessible :deck_id, :erraten, :nachname, :prev_fach, :vorname, :student_id
  validates :vorname, :presence => true,
                      :length => { :minimum => 2}
  validates :nachname, :presence => true,
                       :length => { :minimum => 2 }
 

  belongs_to :deck
  belongs_to :student

  def in_deck?(deck_id)
    deck_id == @deck_id
  end

  def assign_deck(deck_id)
    @deck_id = deck_id
  end




end

app/controllers/karteikartes_controller.rb
class KarteikartesController < ApplicationController
  # GET /karteikartes
  # GET /karteikartes.json
  def index
    @karteikartes = Karteikarte.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @karteikartes }
    end
  end

  # GET /karteikartes/1
  # GET /karteikartes/1.json
  def show
    @karteikarte = Karteikarte.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @karteikarte }
    end
  end

  # GET /karteikartes/new
  # GET /karteikartes/new.json
  def new
    @karteikarte = Karteikarte.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @karteikarte }
    end
  end

  # GET /karteikartes/1/edit
  def edit
    @karteikarte = Karteikarte.find(params[:id])
  end

  # POST /karteikartes
  # POST /karteikartes.json
  def create
    @karteikarte = Karteikarte.new(params[:karteikarte])

    respond_to do |format|
      if @karteikarte.save
        format.html { redirect_to @karteikarte, notice: 'Karteikarte was successfully created.' }
        format.json { render json: @karteikarte, status: :created, location: @karteikarte }
      else
        format.html { render action: "new" }
        format.json { render json: @karteikarte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /karteikartes/1
  # PUT /karteikartes/1.json
  def update
    @karteikarte = Karteikarte.find(params[:id])

    respond_to do |format|
      if @karteikarte.update_attributes(params[:karteikarte])
        format.html { redirect_to @karteikarte, notice: 'Karteikarte was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @karteikarte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /karteikartes/1
  # DELETE /karteikartes/1.json
  def destroy
    @karteikarte = Karteikarte.find(params[:id])
    @karteikarte.destroy

    respond_to do |format|
      format.html { redirect_to karteikartes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/karteikartes_helper.rb
module KarteikartesHelper
end

app/views/karteikartes/_form.html.erb
<%= form_for(@karteikarte) do |f| %>
  <% if @karteikarte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@karteikarte.errors.count, "error") %> prohibited this karteikarte from being saved:</h2>

      <ul>
      <% @karteikarte.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vorname %><br />
    <%= f.text_field :vorname %>
  </div>
  <div class="field">
    <%= f.label :nachname %><br />
    <%= f.text_field :nachname %>
  </div>
  <div class="field">
    <%= f.label :current_fach %><br />
    <%= f.text_field :current_fach %>
  </div>
  <div class="field">
    <%= f.label :prev_fach %><br />
    <%= f.text_field :prev_fach %>
  </div>
  <div class="field">
    <%= f.label :erraten %><br />
    <%= f.check_box :erraten %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/karteikartes/edit.html.erb
<h1>Editing karteikarte</h1>

<%= render 'form' %>

<%= link_to 'Show', @karteikarte %> |
<%= link_to 'Back', karteikartes_path %>

app/views/karteikartes/index.html.erb
<h1>Listing karteikartes</h1>

<table>
  <tr>
    <th>Vorname</th>
    <th>Nachname</th>
    <th>Current fach</th>
    <th>Prev fach</th>
    <th>Erraten</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @karteikartes.each do |karteikarte| %>
  <tr>
    <td><%= karteikarte.vorname %></td>
    <td><%= karteikarte.nachname %></td>
    <td><%= karteikarte.current_fach %></td>
    <td><%= karteikarte.prev_fach %></td>
    <td><%= karteikarte.erraten %></td>
    <td><%= link_to 'Show', karteikarte %></td>
    <td><%= link_to 'Edit', edit_karteikarte_path(karteikarte) %></td>
    <td><%= link_to 'Destroy', karteikarte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Karteikarte', new_karteikarte_path %>

app/views/karteikartes/new.html.erb
<h1>New karteikarte</h1>

<%= render 'form' %>

<%= link_to 'Back', karteikartes_path %>

app/views/karteikartes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Vorname:</b>
  <%= @karteikarte.vorname %>
</p>

<p>
  <b>Nachname:</b>
  <%= @karteikarte.nachname %>
</p>

<p>
  <b>Current fach:</b>
  <%= @karteikarte.current_fach %>
</p>

<p>
  <b>Prev fach:</b>
  <%= @karteikarte.prev_fach %>
</p>

<p>
  <b>Erraten:</b>
  <%= @karteikarte.erraten %>
</p>


<%= link_to 'Edit', edit_karteikarte_path(@karteikarte) %> |
<%= link_to 'Back', karteikartes_path %>